version: '3'
services:
  web:
    build: web2/
    restart: always
    depends_on:
      - server
    ports:
      - "8093:80"

  server:
    build: .
    restart: always
    depends_on:
      - mysql
      - influxdb
      - redis
    volumes:
      - /data/graduation/config:/config

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: graduation
      MYSQL_ROOT_PASSWORD: graduation

  influxdb:
    image: influxdb

  redis:
    image: redis