version: '3'
services:
  web:
    build: web2/
    restart: always
    links:
      - "server:server"
    networks:
      - graduation_net
    ports:
      - "8080:80"
  server:
    build: .
    restart: always
    links:
      - "mysql:mysql"
      - "influxdb:influxdb"
      - "redis:redis"
    depends_on:
      - mysql
      - influxdb
      - redis
    networks:
      - graduation_net
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: graduation
      MYSQL_ROOT_PASSWORD: graduation
  influxdb:
    image: influxdb
  redis:
    image: redis

networks:
  graduation_net: