version: '3'
services:
  server:
    build: deployments
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    depends_on:
      - mysql
      - influxdb
  mysql:
    image: mysql:5.6.35
    ports:
      - "3306:3306"
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      -
