http:
  host: 127.0.0.1
  port: 8080
  allow-origin:
    - "*"
    - "http://127.0.0.1:8080"

influxdb:
  host: localhost
  port: 8086
  dbName: graduation
  password:
  username:

mysql:
  host: localhost
  port: 3307
  dbName: graduation
  username: root
  password: admin

redis:
  host: localhost
  port: 6379
  username:
  password:
  dbName: 0

mail:
  host: smtp.exmail.qq.com
  port: 465
  username: zhaojuwen@deepin.com
  password:

admin:
  mail:
    - 1074687883@qq.com
    - zyvenzhao@163.com
  tel:
    - 15871357810